/**
 * Runs the real Auto-Timesheet pipeline over the synthetic week and writes the
 * payload the prototype page renders.
 *
 * This exists so the prototype is not a mockup: every hour, confidence label and
 * evidence row on that page is produced by `src/core/timesheet/` at build time.
 * If the engine changes, the demo changes.
 *
 *   pnpm run demo:timesheet
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { AttributionEngine } from '../core/timesheet/AttributionEngine.js';
import { BlockSegmenter } from '../core/timesheet/BlockSegmenter.js';
import { ContextSplitter } from '../core/timesheet/ContextSplitter.js';
import { TimesheetSynthesizer, isoDate } from '../core/timesheet/TimesheetSynthesizer.js';
import type { AttributedBlock, EngagementMatcher } from '../core/timesheet/types.js';
import {
  buildSyntheticWeek,
  DEMO_ENGAGEMENTS,
  DEMO_POLICY,
  FIRM_DOMAINS,
} from './syntheticWeek.js';

/** What one accepted correction would teach the engine. */
interface LearningPreview {
  blockId: string;
  suggestedCode: string;
  suggestedLabel: string;
  matchers: EngagementMatcher[];
}

const OUT_DIR = join(process.cwd(), 'prototype', 'timesheet');

function main(): void {
  const signals = buildSyntheticWeek();

  const engine = new AttributionEngine(DEMO_ENGAGEMENTS, DEMO_POLICY, {
    internalDomains: FIRM_DOMAINS,
  });
  const timeBlocks = new BlockSegmenter(DEMO_POLICY).segment(signals);
  const blocks = new ContextSplitter(engine).split(timeBlocks);
  const attributed = engine.attributeAll(blocks);
  const draft = new TimesheetSynthesizer(DEMO_ENGAGEMENTS, DEMO_POLICY).synthesize(attributed);

  const payload = {
    meta: {
      generatedAt: new Date().toISOString(),
      firm: 'Northgate Advisory (fictional)',
      note:
        'Synthetic data. Produced by src/core/timesheet at build time — not hand-authored.',
      policy: DEMO_POLICY,
      weekStart: draft.weekStart,
      days: [...new Set(attributed.map(b => isoDate(b.startedAt, DEMO_POLICY.timeZone)))].sort(),
    },
    engagements: DEMO_ENGAGEMENTS,
    signals,
    blocks: attributed,
    draft,
    learning: learningPreviews(engine, attributed),
    stats: stats(signals, attributed, timeBlocks, draft),
  };

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'demo-data.json'), JSON.stringify(payload, null, 2));
  writeFileSync(
    join(OUT_DIR, 'demo-data.js'),
    `/* Generated by \`pnpm run demo:timesheet\`. Do not edit by hand. */\n` +
      `window.__TIMESHEET_DEMO__ = ${JSON.stringify(payload)};\n`,
  );
  inlineStandalone();

  console.log(
    `demo:timesheet — ${signals.length} signals → ${attributed.length} blocks → ` +
      `${draft.lines.length} timesheet lines (${draft.totalHours}h, ` +
      `${draft.chargeableHours}h chargeable, ` +
      `${Math.round(draft.autoAcceptRatio * 100)}% high-confidence)`,
  );
}

/**
 * For every block the engine could not place confidently, show what accepting a
 * reviewer's correction would teach it.
 *
 * The unassigned blocks are matched to the engagement whose client domain
 * appears in the block, which is what a reviewer would pick — and is exactly the
 * inference the engine refuses to make on its own, because a domain in an
 * invitee list is not authority to bill.
 */
function learningPreviews(
  engine: AttributionEngine,
  blocks: AttributedBlock[],
): LearningPreview[] {
  const out: LearningPreview[] = [];

  for (const block of blocks) {
    if (block.confidence !== 'unattributed' && block.confidence !== 'low') {
      continue;
    }
    const domains = new Set(
      block.signals.flatMap(s => s.participantDomains ?? []).map(d => d.toLowerCase()),
    );
    const candidate = DEMO_ENGAGEMENTS.find(e =>
      [...domains].some(
        d => !FIRM_DOMAINS.includes(d) && d.split('.')[0].startsWith(e.clientName.split(' ')[0].toLowerCase()),
      ),
    );
    if (!candidate) {
      continue;
    }
    const matchers = engine.learnFromCorrection(block, candidate.code);
    if (matchers.length > 0) {
      out.push({
        blockId: block.id,
        suggestedCode: candidate.code,
        suggestedLabel: `${candidate.clientName} — ${candidate.name}`,
        matchers,
      });
    }
  }

  return out;
}

function stats(
  signals: ReturnType<typeof buildSyntheticWeek>,
  blocks: AttributedBlock[],
  timeBlocks: { length: number },
  draft: ReturnType<TimesheetSynthesizer['synthesize']>,
) {
  const observedHours = blocks.reduce((s, b) => s + b.focusSeconds, 0) / 3600;
  const agentMinutes = signals
    .filter(s => s.source === 'agent')
    .reduce((s, sig) => s + (sig.endedAt - sig.startedAt) / 60_000, 0);

  const bySource = new Map<string, number>();
  for (const signal of signals) {
    bySource.set(signal.source, (bySource.get(signal.source) ?? 0) + 1);
  }

  const byEngagement = new Map<string, number>();
  for (const line of draft.lines) {
    byEngagement.set(line.engagementCode, (byEngagement.get(line.engagementCode) ?? 0) + line.hours);
  }

  return {
    signalCount: signals.length,
    blockCount: blocks.length,
    timeBlockCount: timeBlocks.length,
    observedHours: Math.round(observedHours * 100) / 100,
    agentMinutes: Math.round(agentMinutes),
    flowExtendedBlocks: blocks.filter(b => b.flowExtended).length,
    signalsBySource: Object.fromEntries([...bySource.entries()].sort((a, b) => b[1] - a[1])),
    hoursByEngagement: Object.fromEntries(
      [...byEngagement.entries()].sort((a, b) => b[1] - a[1]),
    ),
  };
}

/**
 * Emit a single-file copy with the data inlined, so the prototype can be dropped
 * onto any static host (or opened over file://) as one self-contained page.
 */
function inlineStandalone(): void {
  const indexPath = join(OUT_DIR, 'index.html');
  let html: string;
  try {
    html = readFileSync(indexPath, 'utf8');
  } catch {
    return; // index.html not written yet; nothing to inline.
  }
  for (const asset of ['demo-data.js', 'app.js']) {
    const source = readFileSync(join(OUT_DIR, asset), 'utf8');
    html = html.replace(
      new RegExp(`<script src="\\./${asset.replace('.', '\\.')}"></script>`),
      `<script>\n${source}</script>`,
    );
  }
  writeFileSync(join(OUT_DIR, 'standalone.html'), html);
}

main();
